apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-app-ingress
  annotations:
    kubernetes.io/ingress.allow-http: "true"
spec:
  rules:
    - host: ramazankaragoz.com
      http:
        paths:
          - path: /demo-docker/hello
            backend:
              serviceName: hello-app-service
              servicePort: 80

