apiVersion: v1
kind: Service
metadata:
  name: hello-app-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: hello-app
  type: ClusterIP