apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-app-ingress
spec:
  rules:
    - host: http://35.228.43.199
      http:
        paths:
          - path: /demo-docker
            backend:
              serviceName: hello-app-service
              servicePort: 80

