apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-app-ingress
spec:
  rules:
    - http:
        paths:
          - path: /demo-docker
            backend:
              serviceName: hello-app-service
              servicePort: 80
          - path: /
            backend:
              serviceName: hello-app-service
              servicePort: 80